[project]
name = "ping"
version = "0.1.0"
description = "Personal Discord Bot that sends a message to a text channel when someone joins a voice channel."
readme = "README.md"
authors = [
    { name = "Nevada", email = "migatosellamakiko@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.7.1",
    "python-dotenv>=1.2.2",
    "ruff>=0.16.2",
]

[project.scripts]
ping = "ping:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
